### ISSUE TITLE
[Development Request] Dashboard Displaying Unfiltered Feed

### ISSUE THREAD

**Issue by gktown** [steemit-lol/steemit.lol#4]
**Page:** Dashboard
**Issue:** Currently all steemit images are being displayed
**Proposed Solution:** Filter all dashboard images except Steemit.lol memes

To avoid people posting to steemit.lol dashboard using the steemitlol tag from steemit, this issue may require some work in the post creator.

**Comment by Rishi556** [comment]
https://github.com/steemit-lol/steemit.lol/pull/13 Should do it.

**Comment by Kennybll** [comment]
Thanks @Rishi556
